services:
  web:
    build: .
    container_name: webstudio
    restart: always
    ports:
      - "3000:3000"
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`haeicore.com.br`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=letsencrypt"

networks:
  dokploy-network:
    external: true
